package gym_project.view;

import database.DB;
import gym_project.controller.memberDao;
import static gym_project.controller.memberDao.Delete_Member;
import gym_project.model.Member;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class EditMemberPage extends javax.swing.JFrame {

    /**
     * Creates new form EditMemberPage
     */
    public EditMemberPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MembershipText = new javax.swing.JLabel();
        MemberIDText = new javax.swing.JLabel();
        MemberIDTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        FirstNameText = new javax.swing.JLabel();
        LastNameText = new javax.swing.JLabel();
        AgeText = new javax.swing.JLabel();
        DOBText = new javax.swing.JLabel();
        AddressText = new javax.swing.JLabel();
        FirstNameText5 = new javax.swing.JLabel();
        PhoneNoText = new javax.swing.JLabel();
        PaymentText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        TrainerCategoryText = new javax.swing.JLabel();
        GymTimeText = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        PhoneNoField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        DatechooserText = new com.toedter.calendar.JDateChooser();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        TrainerCategoryComboBox = new javax.swing.JComboBox<>();
        GymTimeComboBox = new javax.swing.JComboBox<>();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        AgeField = new javax.swing.JTextField();
        MemberhsipDurationComboBox = new javax.swing.JLabel();
        MembershipDurationCBox = new javax.swing.JComboBox<>();
        CardioCentralText = new javax.swing.JLabel();
        HomeOfFitnessText = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        image5Field = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 101, 130));
        setLocation(300,100);

        jPanel2.setBackground(new java.awt.Color(4, 101, 130));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        MembershipText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MembershipText.setForeground(new java.awt.Color(255, 255, 255));
        MembershipText.setText("MEMBERSHIP REGISTRATION");

        MemberIDText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MemberIDText.setForeground(new java.awt.Color(255, 255, 255));
        MemberIDText.setText("Member ID:");

        MemberIDTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        SearchButton.setBackground(new java.awt.Color(57, 20, 162));
        SearchButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        FirstNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameText.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameText.setText("First Name:");

        LastNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastNameText.setForeground(new java.awt.Color(255, 255, 255));
        LastNameText.setText("Last Name:");

        AgeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AgeText.setForeground(new java.awt.Color(255, 255, 255));
        AgeText.setText("Age:");

        DOBText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DOBText.setForeground(new java.awt.Color(255, 255, 255));
        DOBText.setText("Date of Birth:");

        AddressText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddressText.setForeground(new java.awt.Color(255, 255, 255));
        AddressText.setText("Address:");

        FirstNameText5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameText5.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameText5.setText("Gender:");

        PhoneNoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNoText.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNoText.setText("Phone Number:");

        PaymentText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PaymentText.setForeground(new java.awt.Color(255, 255, 255));
        PaymentText.setText("Payment(Monthly):");

        EmailText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setText("Email:");

        TrainerCategoryText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TrainerCategoryText.setForeground(new java.awt.Color(255, 255, 255));
        TrainerCategoryText.setText("Trainer Category:");

        GymTimeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeText.setForeground(new java.awt.Color(255, 255, 255));
        GymTimeText.setText("Gym Time:");

        buttonGroup1.add(MaleRadioButton);
        MaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        MaleRadioButton.setText("Male");
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(FemaleRadioButton);
        FemaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FemaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        TrainerCategoryComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TrainerCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Fitness Instructor" }));
        TrainerCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerCategoryComboBoxActionPerformed(evt);
            }
        });

        GymTimeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Evening" }));
        GymTimeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymTimeComboBoxActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(57, 20, 162));
        UpdateButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update ");
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseClicked(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(57, 20, 162));
        DeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(57, 20, 162));
        ResetButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        MemberhsipDurationComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MemberhsipDurationComboBox.setForeground(new java.awt.Color(255, 255, 255));
        MemberhsipDurationComboBox.setText("Membership Duration:");

        MembershipDurationCBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MembershipDurationCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Annual", "6 Month" }));
        MembershipDurationCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembershipDurationCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressText)
                                    .addComponent(PhoneNoText)
                                    .addComponent(GymTimeText)
                                    .addComponent(AgeText)
                                    .addComponent(PaymentText)
                                    .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstNameText)
                                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DOBText)
                                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameText)
                                    .addComponent(DatechooserText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(FirstNameText5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaleRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(FemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EmailText)
                                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UpdateButton)
                                    .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(DeleteButton)
                                        .addGap(56, 56, 56)
                                        .addComponent(ResetButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TrainerCategoryText)
                                            .addComponent(TrainerCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MembershipDurationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MemberhsipDurationComboBox)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(MembershipText))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(MemberIDText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MemberIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(SearchButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MembershipText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberIDText)
                    .addComponent(MemberIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameText)
                    .addComponent(LastNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOBText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatechooserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText)
                    .addComponent(FirstNameText5)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNoText)
                            .addComponent(EmailText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(PaymentText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MemberhsipDurationComboBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MembershipDurationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GymTimeText)
                    .addComponent(TrainerCategoryText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainerCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(ResetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardioCentralText.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CardioCentralText.setForeground(new java.awt.Color(255, 255, 255));
        CardioCentralText.setText("Cardio Central");

        HomeOfFitnessText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HomeOfFitnessText.setForeground(new java.awt.Color(255, 255, 255));
        HomeOfFitnessText.setText("Home of Fitness");

        BackButton.setBackground(new java.awt.Color(57, 20, 162));
        BackButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(57, 20, 162));
        ExitButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        image5Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_project/images/image5.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(CardioCentralText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExitButton)
                                    .addComponent(BackButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(HomeOfFitnessText)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(image5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(CardioCentralText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeOfFitnessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(image5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addGap(53, 53, 53))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GymTimeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymTimeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GymTimeComboBoxActionPerformed

    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void TrainerCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerCategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerCategoryComboBoxActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Dashboard ss = new Dashboard();
        ss.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new EditMemberPage().setVisible(true);


    }//GEN-LAST:event_ResetButtonActionPerformed

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        // TODO add your handling code here:
        int checkId = 0;
        String member_id = MemberIDTextField.getText();
        //String member_id1 = MemberIDTextField.getText();
        boolean memberFound = false;

        try {
            Connection con = DB.connect();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from member where member_id='" + member_id + "'");
            while (rs.next()) {
                FirstNameField.setText(rs.getString("first_name"));
                LastNameField.setText(rs.getString("last_name"));
                AgeField.setText(String.valueOf(rs.getInt("age")));
                DatechooserText.setDate(rs.getDate("date_of_birth"));
                AddressField.setText(rs.getString("address"));
                if (rs.getString("gender").equals("Male")) {
                    MaleRadioButton.setSelected(true);
                    FemaleRadioButton.setSelected(false);
                }
                else {
                    MaleRadioButton.setSelected(false);
                    FemaleRadioButton.setSelected(true);
                }
                PhoneNoField.setText(rs.getString("phoneNumber"));
                EmailField.setText(rs.getString("email"));
                PaymentField.setText(rs.getString("payment"));
                TrainerCategoryComboBox.setSelectedItem(rs.getString("trainer_category"));
                GymTimeComboBox.setSelectedItem(rs.getString("gym_time"));
                
               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection error");
        }
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void UpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseClicked
        // TODO add your handling code here:
        
            String regex = "\\d{10}";
         if(FirstNameField.getText().equals("")
            || LastNameField.getText().equals("") 
            || AgeField.getText().equals("")
            ||  DatechooserText.getDate()==null
            ||  AddressField.getText().equals("")
            || PhoneNoField.getText().equals("")
            || EmailField.getText().equals("")
            || PaymentField.getText().equals("")
            || MembershipDurationCBox.getSelectedItem()==null
            || GymTimeComboBox.getSelectedItem() == null
            || TrainerCategoryComboBox.getSelectedItem() == null   ){
                JOptionPane.showMessageDialog(null, "Unfilled Credentials");

        }else if(!(PhoneNoField.getText().matches(regex))){
            JOptionPane.showMessageDialog(rootPane, "Invalid Contact. Enter contact number with 10 digits and no characters ");
        }else if(!(EmailField.getText().endsWith(".com")) || !(EmailField.getText().contains("@"))) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Email Format");
        }
        
        else{
        String first_name = FirstNameField.getText();
        String last_name = LastNameField.getText();
        int age = Integer.parseInt(AgeField.getText());
        java.util.Date date_of_birth = DatechooserText.getDate();
        String address = AddressField.getText();
        String gender;
        if (MaleRadioButton.isSelected()) {
            gender = "Male";
        } else if (FemaleRadioButton.isSelected()) {
            gender = "Female";
        } else {
            gender = "none";
        }
        int membership_duration = 0;
        if(MembershipDurationCBox.getSelectedItem().equals("Monthly")){
            membership_duration = 1;
        }else if(MembershipDurationCBox.getSelectedItem().equals("Annual")){
            membership_duration = 12;
        }else if(MembershipDurationCBox.getSelectedItem().equals("Six Months")){
            membership_duration = 6;}
        String phone_number= PhoneNoField.getText();
        String email = EmailField.getText();
        int payment = Integer.parseInt(PaymentField.getText());
        
        String gym_time = (String) GymTimeComboBox.getSelectedItem();
        String trainer = (String) TrainerCategoryComboBox.getSelectedItem();
        setVisible(false);
        new EditMemberPage().setVisible(true);
        
       int  member_id = Integer.parseInt(MemberIDTextField.getText());
        Member member  = new Member(first_name, last_name,  age,  address,  phone_number,  email, membership_duration, gym_time,   payment,  date_of_birth,  trainer,  gender );
        try {
            memberDao.updateMember_Page(member, member_id);
          JOptionPane.showMessageDialog(rootPane, "You have update member details successfully");
            
        } catch (SQLException ex) {
            System.out.println("Error");
            Logger.getLogger(EditMemberPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
    }//GEN-LAST:event_UpdateButtonMouseClicked

    private void MembershipDurationCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembershipDurationCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MembershipDurationCBoxActionPerformed

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        // TODO add your handling code here:
        int member_id = Integer.parseInt(MemberIDTextField.getText());
        try {
            Delete_Member(member_id);
            setVisible(false);
             new EditMemberPage().setVisible(true);
             JOptionPane.showMessageDialog(rootPane, "The member is deleted successfully");
        } catch (SQLException ex) {
            Logger.getLogger(EditMemberPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DeleteButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMemberPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressText;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeText;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CardioCentralText;
    private javax.swing.JLabel DOBText;
    private com.toedter.calendar.JDateChooser DatechooserText;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel FirstNameText5;
    private javax.swing.JComboBox<String> GymTimeComboBox;
    private javax.swing.JLabel GymTimeText;
    private javax.swing.JLabel HomeOfFitnessText;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel MemberIDText;
    private javax.swing.JTextField MemberIDTextField;
    private javax.swing.JLabel MemberhsipDurationComboBox;
    private javax.swing.JComboBox<String> MembershipDurationCBox;
    private javax.swing.JLabel MembershipText;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JLabel PaymentText;
    private javax.swing.JTextField PhoneNoField;
    private javax.swing.JLabel PhoneNoText;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JComboBox<String> TrainerCategoryComboBox;
    private javax.swing.JLabel TrainerCategoryText;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image5Field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
