/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_project.view;

import database.DB;
import gym_project.controller.memberDao;
import static gym_project.controller.memberDao.Delete_Member;
import gym_project.controller.trainerDao;
//import static gym_project.controller.trainerDao.Delete_Trainer;
import gym_project.model.Member;
import gym_project.model.Trainer;
import gym_project.view.EditMemberPage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author user
 */
public class EditTrainerPage extends javax.swing.JFrame {

    /**
     * Creates new form EditTrainerPage
     */
    public EditTrainerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FirstNameText = new javax.swing.JLabel();
        LastNameText = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        AgeText = new javax.swing.JLabel();
        DOBText = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        DatechooserText = new com.toedter.calendar.JDateChooser();
        AddressText = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        GenderText = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        PhoneNoText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        PhoneNoField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        DurationText = new javax.swing.JLabel();
        DurationComboBox = new javax.swing.JComboBox<>();
        CategoryText = new javax.swing.JLabel();
        CategoryComboBox = new javax.swing.JComboBox<>();
        GymTimeText = new javax.swing.JLabel();
        GymTimeComboBox = new javax.swing.JComboBox<>();
        UpdateButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        CardioCentralText = new javax.swing.JLabel();
        HomeOfFitnessText = new javax.swing.JLabel();
        HomeOfFitnessText1 = new javax.swing.JLabel();
        TrainerIDText = new javax.swing.JLabel();
        TrainerIDField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        imageField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 101, 130));
        setLocation(300,100);

        jPanel2.setBackground(new java.awt.Color(4, 101, 130));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        FirstNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameText.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameText.setText("First Name:");

        LastNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastNameText.setForeground(new java.awt.Color(255, 255, 255));
        LastNameText.setText("Last Name:");

        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });

        AgeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AgeText.setForeground(new java.awt.Color(255, 255, 255));
        AgeText.setText("Age:");

        DOBText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DOBText.setForeground(new java.awt.Color(255, 255, 255));
        DOBText.setText("Date of Birth:");

        AddressText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddressText.setForeground(new java.awt.Color(255, 255, 255));
        AddressText.setText("Address:");

        GenderText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GenderText.setForeground(new java.awt.Color(255, 255, 255));
        GenderText.setText("Gender:");

        buttonGroup1.add(MaleRadioButton);
        MaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaleRadioButton.setText("Male");

        buttonGroup1.add(FemaleRadioButton);
        FemaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FemaleRadioButton.setText("Female");

        PhoneNoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNoText.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNoText.setText("Phone Number:");

        EmailText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setText("Email:");

        DurationText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DurationText.setForeground(new java.awt.Color(255, 255, 255));
        DurationText.setText("Duration(Months):");

        DurationComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DurationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "6 Months" }));

        CategoryText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CategoryText.setForeground(new java.awt.Color(255, 255, 255));
        CategoryText.setText("Category:");

        CategoryComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Fitness Instructor" }));

        GymTimeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeText.setForeground(new java.awt.Color(255, 255, 255));
        GymTimeText.setText("Gym Time:");

        GymTimeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Evening" }));

        UpdateButton.setBackground(new java.awt.Color(57, 20, 162));
        UpdateButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseClicked(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(57, 20, 162));
        ResetButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(UpdateButton)
                        .addGap(60, 60, 60)
                        .addComponent(ResetButton))
                    .addComponent(GymTimeText)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GymTimeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DurationComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(AgeText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(AddressText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNoText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addComponent(DurationText)))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CategoryText)
                            .addComponent(EmailText)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GenderText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FemaleRadioButton))
                            .addComponent(DatechooserText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBText)
                            .addComponent(LastNameText)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CategoryComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameText)
                    .addComponent(LastNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBText)
                    .addComponent(AgeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatechooserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText)
                    .addComponent(GenderText)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoText)
                    .addComponent(EmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurationText)
                    .addComponent(CategoryText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(GymTimeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardioCentralText.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CardioCentralText.setForeground(new java.awt.Color(255, 255, 255));
        CardioCentralText.setText("Cardio Central");

        HomeOfFitnessText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HomeOfFitnessText.setForeground(new java.awt.Color(255, 255, 255));
        HomeOfFitnessText.setText("Home of Fitness");

        HomeOfFitnessText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HomeOfFitnessText1.setForeground(new java.awt.Color(255, 255, 255));
        HomeOfFitnessText1.setText("TRAINER REGISTRATION");

        TrainerIDText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TrainerIDText.setForeground(new java.awt.Color(255, 255, 255));
        TrainerIDText.setText("Trainer ID:");

        TrainerIDField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        SearchButton.setBackground(new java.awt.Color(57, 20, 162));
        SearchButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(57, 20, 162));
        BackButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(57, 20, 162));
        ExitButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        imageField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_project/images/image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeOfFitnessText)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExitButton)
                                    .addComponent(BackButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CardioCentralText)
                        .addGap(144, 144, 144)
                        .addComponent(TrainerIDText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrainerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeOfFitnessText1)))
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HomeOfFitnessText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardioCentralText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TrainerIDText)
                        .addComponent(TrainerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HomeOfFitnessText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BackButton)
                        .addGap(18, 18, 18)
                        .addComponent(ExitButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
       Dashboard ss = new Dashboard();
       ss.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        int checkId = 0;
        String trainer_id = TrainerIDField.getText();

        try {
            Connection con = DB.connect();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from trainer where trainer_id=" + trainer_id );
            while (rs.next()) {
                FirstNameField.setText(rs.getString("first_name"));
                LastNameField.setText(rs.getString("last_name"));
                AgeField.setText(String.valueOf(rs.getInt("age")));
                DatechooserText.setDate(rs.getDate("Date_of_birth"));
                AddressField.setText(rs.getString("address"));
                if (rs.getString("gender").equals("Male")) {
                    MaleRadioButton.setSelected(true);
                    FemaleRadioButton.setSelected(false);
                } else {
                    MaleRadioButton.setSelected(false);
                    FemaleRadioButton.setSelected(true);
                }
                PhoneNoField.setText(rs.getString("phone_number"));
                EmailField.setText(rs.getString("email"));
                //PaymentField.setText(rs.getString("payment"));
                CategoryComboBox.setSelectedItem(rs.getString("category"));
                GymTimeComboBox.setSelectedItem(rs.getString("gym_time"));
                
                
            }
        } catch (SQLException e) {
             Logger.getLogger(EditTrainerPage.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "connection error");


       }
    

        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseClicked
        // TODO add your handling code here:
        
        String regex = "\\d{10}";

// Check for unfilled fields
if (FirstNameField.getText().equals("")
    || LastNameField.getText().equals("") 
    || AgeField.getText().equals("")
    || DatechooserText.getDate() == null
    || AddressField.getText().equals("")
    || PhoneNoField.getText().equals("")
    || EmailField.getText().equals("")
    || DurationComboBox.getSelectedItem() == null
    || GymTimeComboBox.getSelectedItem() == null
    || CategoryComboBox.getSelectedItem() == null) {
    
    JOptionPane.showMessageDialog(null, "Unfilled Credentials");

} else if (!(PhoneNoField.getText().matches(regex))) {
    // Check for valid phone number
    JOptionPane.showMessageDialog(rootPane, "Invalid Contact. Enter a contact number with 10 digits and no characters.");

} else if (!(EmailField.getText().endsWith(".com")) || !(EmailField.getText().contains("@"))) {
    // Check for valid email format
    JOptionPane.showMessageDialog(rootPane, "Invalid Email Format");

} else {
    // Valid inputs, proceed to update the trainer
    String first_name = FirstNameField.getText();
    String last_name = LastNameField.getText();
    int age = Integer.parseInt(AgeField.getText());
    java.util.Date date_of_birth = DatechooserText.getDate();
    String address = AddressField.getText();
    String gender;

    if (MaleRadioButton.isSelected()) {
        gender = "Male";
    } else if (FemaleRadioButton.isSelected()) {
        gender = "Female";
    } else {
        gender = "none";
    }

    String duration = (String) DurationComboBox.getSelectedItem();
    String phone_number = PhoneNoField.getText();
    String email = EmailField.getText();
    String gym_time = (String) GymTimeComboBox.getSelectedItem();
    String category = (String) CategoryComboBox.getSelectedItem();
    int trainer_id = Integer.parseInt(TrainerIDField.getText());

    // Create a Trainer object with the updated values
    Trainer trainers = new Trainer(first_name, last_name, age, date_of_birth, address, gender, phone_number, email, duration, gym_time, category);

    try {
        // Update the trainer information in the database, including the duration
        trainerDao.updateTrainer_Page(trainers, trainer_id);
        JOptionPane.showMessageDialog(rootPane, "Trainer updated successfully");

        // Optionally, you can clear the fields after updating
        FirstNameField.setText("");
        LastNameField.setText("");
        AgeField.setText("");
        DatechooserText.setDate(null);
        AddressField.setText("");
        PhoneNoField.setText("");
        EmailField.setText("");
        DurationComboBox.setSelectedItem(null);
        GymTimeComboBox.setSelectedItem(null);
        CategoryComboBox.setSelectedItem(null);
        TrainerIDField.setText("");
        
    } catch (SQLException ex) {
        Logger.getLogger(EditTrainerPage.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(rootPane, "Error occurred while updating the trainer.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

        

    }//GEN-LAST:event_UpdateButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new EditTrainerPage().setVisible(true);
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTrainerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressText;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeText;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CardioCentralText;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JLabel CategoryText;
    private javax.swing.JLabel DOBText;
    private com.toedter.calendar.JDateChooser DatechooserText;
    private javax.swing.JComboBox<String> DurationComboBox;
    private javax.swing.JLabel DurationText;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel GenderText;
    private javax.swing.JComboBox<String> GymTimeComboBox;
    private javax.swing.JLabel GymTimeText;
    private javax.swing.JLabel HomeOfFitnessText;
    private javax.swing.JLabel HomeOfFitnessText1;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JTextField PhoneNoField;
    private javax.swing.JLabel PhoneNoText;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField TrainerIDField;
    private javax.swing.JLabel TrainerIDText;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imageField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
