/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_project.view;

import gym_project.controller.AdminDao;
import gym_project.controller.memberDao;
import gym_project.model.Admin;
import gym_project.model.Member;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



    


/**
 *
 * @author user
 */
public class Membershipadd extends javax.swing.JFrame {

    /**
     * Creates new form Membershipadd
     */
    public Membershipadd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MembershipText = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JLabel();
        LastNameText = new javax.swing.JLabel();
        AgeText = new javax.swing.JLabel();
        DOBText = new javax.swing.JLabel();
        AddressText = new javax.swing.JLabel();
        GenderFeild = new javax.swing.JLabel();
        PhoneNoText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        PaymentText = new javax.swing.JLabel();
        GymTimeText = new javax.swing.JLabel();
        MemberhsipDurationComboBox = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        GymTimeComboBox = new javax.swing.JComboBox<>();
        MembershipDurationCBox = new javax.swing.JComboBox<>();
        LastNameFIeld = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        FirstNameFIeld2 = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        PhoneNoField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        TrainerCategory = new javax.swing.JLabel();
        TrainerCategoryComboBox2 = new javax.swing.JComboBox<>();
        CardioText = new javax.swing.JLabel();
        HomeOfFitnessText = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        Image1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 101, 130));
        setLocation(300,80);

        jPanel2.setBackground(new java.awt.Color(4, 101, 130));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        MembershipText.setBackground(new java.awt.Color(57, 20, 162));
        MembershipText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MembershipText.setForeground(new java.awt.Color(255, 255, 255));
        MembershipText.setText("MEMBERSHIP REGISTRATION");

        FirstNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameText.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameText.setText("First Name:");

        LastNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastNameText.setForeground(new java.awt.Color(255, 255, 255));
        LastNameText.setText("Last Name:");

        AgeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AgeText.setForeground(new java.awt.Color(255, 255, 255));
        AgeText.setText("Age:");

        DOBText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DOBText.setForeground(new java.awt.Color(255, 255, 255));
        DOBText.setText("Date of Birth:");

        AddressText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddressText.setForeground(new java.awt.Color(255, 255, 255));
        AddressText.setText("Address:");

        GenderFeild.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GenderFeild.setForeground(new java.awt.Color(255, 255, 255));
        GenderFeild.setText("Gender:");

        PhoneNoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNoText.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNoText.setText("Phone Number:");

        EmailText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setText("Email:");

        PaymentText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PaymentText.setForeground(new java.awt.Color(255, 255, 255));
        PaymentText.setText("Payment(Monthly):");

        GymTimeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeText.setForeground(new java.awt.Color(255, 255, 255));
        GymTimeText.setText("Gym Time:");

        MemberhsipDurationComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MemberhsipDurationComboBox.setForeground(new java.awt.Color(255, 255, 255));
        MemberhsipDurationComboBox.setText("Membership Duration:");

        MaleRadioButton.setBackground(new java.awt.Color(4, 101, 130));
        buttonGroup1.add(MaleRadioButton);
        MaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        MaleRadioButton.setText("Male");

        jRadioButton1.setBackground(new java.awt.Color(4, 101, 130));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Female");

        GymTimeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Evening" }));
        GymTimeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymTimeComboBoxActionPerformed(evt);
            }
        });

        MembershipDurationCBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MembershipDurationCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Annual", "6 Month" }));
        MembershipDurationCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembershipDurationCBoxActionPerformed(evt);
            }
        });

        LastNameFIeld.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastNameFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFIeldActionPerformed(evt);
            }
        });

        AgeField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFieldActionPerformed(evt);
            }
        });

        FirstNameFIeld2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameFIeld2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFIeld2ActionPerformed(evt);
            }
        });

        AddressField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        PhoneNoField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoFieldActionPerformed(evt);
            }
        });

        EmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        PaymentField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PaymentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentFieldActionPerformed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(57, 20, 162));
        RegisterButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(57, 20, 162));
        ResetButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TrainerCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TrainerCategory.setForeground(new java.awt.Color(255, 255, 255));
        TrainerCategory.setText("Trainer Category: ");

        TrainerCategoryComboBox2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TrainerCategoryComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Fitness Instructor" }));
        TrainerCategoryComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerCategoryComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameText)
                                    .addComponent(AgeText)
                                    .addComponent(AddressText)
                                    .addComponent(PhoneNoText)
                                    .addComponent(PaymentText)
                                    .addComponent(GymTimeText)
                                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstNameFIeld2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RegisterButton)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailText)
                            .addComponent(LastNameText)
                            .addComponent(DOBText)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GenderFeild)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1))
                            .addComponent(ResetButton)
                            .addComponent(MembershipDurationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LastNameFIeld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addComponent(MemberhsipDurationComboBox)
                            .addComponent(TrainerCategory)
                            .addComponent(TrainerCategoryComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(MembershipText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(MembershipText)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameText)
                    .addComponent(LastNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameFIeld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeText)
                    .addComponent(DOBText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText)
                    .addComponent(GenderFeild)
                    .addComponent(MaleRadioButton)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoText)
                    .addComponent(EmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentText)
                    .addComponent(MemberhsipDurationComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MembershipDurationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GymTimeText)
                    .addComponent(TrainerCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainerCategoryComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(ResetButton))
                .addGap(76, 76, 76))
        );

        CardioText.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CardioText.setForeground(new java.awt.Color(255, 255, 255));
        CardioText.setText("Cardio Central");

        HomeOfFitnessText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HomeOfFitnessText.setForeground(new java.awt.Color(255, 255, 255));
        HomeOfFitnessText.setText("Home of Fitness");

        BackButton.setBackground(new java.awt.Color(57, 20, 162));
        BackButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(57, 20, 162));
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        Image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_project/images/image1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton)
                            .addComponent(HomeOfFitnessText)
                            .addComponent(ExitButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(CardioText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(CardioText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeOfFitnessText)
                .addGap(18, 18, 18)
                .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addGap(73, 73, 73))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GymTimeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymTimeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GymTimeComboBoxActionPerformed

    private void MembershipDurationCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembershipDurationCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MembershipDurationCBoxActionPerformed

    private void AgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFieldActionPerformed

    private void FirstNameFIeld2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFIeld2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFIeld2ActionPerformed

    private void LastNameFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFIeldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void PhoneNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void PaymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentFieldActionPerformed

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
         String regex = "\\d{10}";
        if(FirstNameFIeld2.getText().equals("")
            || LastNameFIeld.getText().equals("") 
            || AgeField.getText().equals("")
            || jDateChooser1.getDate()==null
            ||  AddressField.getText().equals("")
            || PhoneNoField.getText().equals("")
            || EmailField.getText().equals("")
            || PaymentField.getText().equals("")
            || MembershipDurationCBox.getSelectedItem()==null
            || GymTimeComboBox.getSelectedItem() == null
            || TrainerCategoryComboBox2.getSelectedItem() == null   ){
                JOptionPane.showMessageDialog(null, "Unfilled Credentials");

        }else if(!(PhoneNoField.getText().matches(regex))){
            JOptionPane.showMessageDialog(rootPane, "Invalid Contact. Enter contact number with 10 digits and no characters ");
        }else if(!(EmailField.getText().endsWith(".com")) || !(EmailField.getText().contains("@"))) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Email Format");
        }
         else{
        
        String first_name = FirstNameFIeld2.getText();
        String last_name= LastNameFIeld.getText();
        int age = Integer.parseInt(AgeField.getText());
        Date date_of_birth  = jDateChooser1.getDate();
        String address = AddressField.getText();
        String gender;
        if(MaleRadioButton.isSelected()){
        gender = "Male";
        }else if(jRadioButton1.isSelected()){
        gender = "Female";
        }else{
            gender = "none";
        }
        String phone_number = PhoneNoField.getText();
        String email = EmailField.getText();
        int payment = Integer.parseInt(PaymentField.getText());
        int membership_duration = 0;
        if(MembershipDurationCBox.getSelectedItem().equals("Monthly")){
            membership_duration = 1;
        }else if(MembershipDurationCBox.getSelectedItem().equals("Annual")){
            membership_duration = 12;
        }else if(MembershipDurationCBox.getSelectedItem().equals("Six Months")){
            membership_duration = 6;}
        String gym_time = (String) GymTimeComboBox.getSelectedItem();
        String trainer = (String) TrainerCategoryComboBox2.getSelectedItem();

         Member  memberInput = new Member(first_name, last_name, age,  address ,  phone_number,  email,  payment, 
                  gym_time, membership_duration,  date_of_birth,  trainer, gender);
         
         FirstNameFIeld2.setText("");
         LastNameFIeld.getText();
          AgeField.setText("");
        jDateChooser1.setDate(null);
        AddressField.setText("");
        MaleRadioButton.setSelected(false);
        jRadioButton1.setSelected(false);
        PhoneNoField.setText("");
        EmailField.setText("");
        PaymentField.setText("");
        TrainerCategoryComboBox2.setSelectedItem(null);
        GymTimeComboBox.setSelectedItem(null);
        MembershipDurationCBox.setSelectedItem(null);
        //System.out.println("Member registerd successfully.");
        JOptionPane.showMessageDialog(null,"Member Registered Sucessfully. ");
        
         
        try {
            memberDao.addMember(memberInput);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        

                        
        }
        
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Dashboard ss = new Dashboard();
        ss.setVisible(true);
        
    }//GEN-LAST:event_BackButtonMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        FirstNameFIeld2.setText("");
        LastNameFIeld.setText("");
        AgeField.setText("");
        jDateChooser1.setDate(null);
        AddressField.setText("");
        MaleRadioButton.setSelected(false);
        jRadioButton1.setSelected(false);
        PhoneNoField.setText("");
        EmailField.setText("");
        PaymentField.setText("");
        TrainerCategoryComboBox2.setSelectedItem(null);
        GymTimeComboBox.setSelectedItem(null);
        MembershipDurationCBox.setSelectedItem(null);
        
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void TrainerCategoryComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerCategoryComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerCategoryComboBox2ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dashboard ss = new Dashboard();
        ss.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membershipadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membershipadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membershipadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membershipadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membershipadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressText;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeText;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CardioText;
    private javax.swing.JLabel DOBText;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FirstNameFIeld2;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel GenderFeild;
    private javax.swing.JComboBox<String> GymTimeComboBox;
    private javax.swing.JLabel GymTimeText;
    private javax.swing.JLabel HomeOfFitnessText;
    private javax.swing.JLabel Image1;
    private javax.swing.JTextField LastNameFIeld;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel MemberhsipDurationComboBox;
    private javax.swing.JComboBox<String> MembershipDurationCBox;
    private javax.swing.JLabel MembershipText;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JLabel PaymentText;
    private javax.swing.JTextField PhoneNoField;
    private javax.swing.JLabel PhoneNoText;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel TrainerCategory;
    private javax.swing.JComboBox<String> TrainerCategoryComboBox2;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
