/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_project.view;

import database.DB;
import gym_project.controller.trainerDao;
import gym_project.model.Trainer;
import gym_project.model.Admin;
import gym_project.model.Trainer;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author user
 */
public class TrainerAdd extends javax.swing.JFrame {

    /**
     * Creates new form TrainerAdd
     */
    public TrainerAdd() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TrainerRegText = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JLabel();
        LastNameText = new javax.swing.JLabel();
        AgeText = new javax.swing.JLabel();
        DOBText = new javax.swing.JLabel();
        AddressText = new javax.swing.JLabel();
        GenderTextField = new javax.swing.JLabel();
        PhoneNoText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        DurationText = new javax.swing.JLabel();
        GymTimeText = new javax.swing.JLabel();
        CategoryText = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        RegisterButton1 = new javax.swing.JButton();
        FirstNameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        GymTimeComboBox = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        DurationComboBox = new javax.swing.JComboBox<>();
        JCalender = new com.toedter.calendar.JDateChooser();
        CardioText = new javax.swing.JLabel();
        HomeofFintessText = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(4, 101, 130));
        setLocation(300,80);

        jPanel5.setBackground(new java.awt.Color(4, 101, 130));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TrainerRegText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainerRegText.setForeground(new java.awt.Color(255, 255, 255));
        TrainerRegText.setText("TRAINER REGISTRATION");

        FirstNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstNameText.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameText.setText("First Name:");

        LastNameText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastNameText.setForeground(new java.awt.Color(255, 255, 255));
        LastNameText.setText("Last Name:");

        AgeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AgeText.setForeground(new java.awt.Color(255, 255, 255));
        AgeText.setText("Age:");

        DOBText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DOBText.setForeground(new java.awt.Color(255, 255, 255));
        DOBText.setText("Date of Birth:");
        DOBText.setToolTipText("");

        AddressText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddressText.setForeground(new java.awt.Color(255, 255, 255));
        AddressText.setText("Address:");

        GenderTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GenderTextField.setForeground(new java.awt.Color(255, 255, 255));
        GenderTextField.setText("Gender:");

        PhoneNoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNoText.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNoText.setText("Phone Number:");

        EmailText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setText("Email:");

        DurationText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DurationText.setForeground(new java.awt.Color(255, 255, 255));
        DurationText.setText("Duration:");

        GymTimeText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeText.setForeground(new java.awt.Color(255, 255, 255));
        GymTimeText.setText("Gym Time:");

        CategoryText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CategoryText.setForeground(new java.awt.Color(255, 255, 255));
        CategoryText.setText("Category:");

        RegisterButton.setBackground(new java.awt.Color(57, 20, 162));
        RegisterButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        RegisterButton1.setBackground(new java.awt.Color(57, 20, 162));
        RegisterButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegisterButton1.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton1.setText("Reset");
        RegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButton1ActionPerformed(evt);
            }
        });

        FirstNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AgeField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        LastNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AddressField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        PhoneField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        EmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        buttonGroup1.add(MaleRadioButton);
        MaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        MaleRadioButton.setText("Male");
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(FemaleRadioButton);
        FemaleRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FemaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRadioButton.setText("Female");

        GymTimeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GymTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Evening" }));

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Fitness Instructor" }));

        DurationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yearly", "6 Month" }));

        JCalender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(TrainerRegText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameText)
                            .addComponent(AgeText)
                            .addComponent(AddressText)
                            .addComponent(PhoneNoText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeField)
                            .addComponent(FirstNameField)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(PhoneField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(AddressField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(DurationText)
                                    .addComponent(GymTimeText)
                                    .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DurationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(105, 105, 105)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameText)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(GenderTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MaleRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FemaleRadioButton))
                            .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(RegisterButton1))
                            .addComponent(DOBText))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JCalender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CategoryText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailField)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 135, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TrainerRegText)
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameText)
                    .addComponent(LastNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOBText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText)
                    .addComponent(GenderTextField)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoText)
                    .addComponent(EmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurationText)
                    .addComponent(CategoryText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(GymTimeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GymTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton1)
                    .addComponent(RegisterButton))
                .addGap(32, 32, 32))
        );

        CardioText.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CardioText.setForeground(new java.awt.Color(255, 255, 255));
        CardioText.setText("Cardio Central");

        HomeofFintessText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HomeofFintessText.setForeground(new java.awt.Color(255, 255, 255));
        HomeofFintessText.setText("Home of Fitness");

        ExitButton.setBackground(new java.awt.Color(57, 20, 162));
        ExitButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(57, 20, 162));
        backButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_project/images/image3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(HomeofFintessText))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(CardioText))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExitButton)
                                    .addComponent(backButton))))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CardioText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeofFintessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(40, 40, 40))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButton1ActionPerformed
        // TODO add your handling code here:
        FirstNameField.setText("");
        LastNameField.setText("");
        AgeField.setText("");
        JCalender.setDate(null);
        AddressField.setText("");
        GenderTextField.setText("");
        PhoneField.setText("");
        EmailField.setText("");
        DurationComboBox.setSelectedItem(null);
        //TrainerIDField.setText("");
        GymTimeComboBox.setSelectedItem(null);
        jComboBox1.setSelectedItem(null);
        
        
    }//GEN-LAST:event_RegisterButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dashboard ss = new Dashboard();
        ss.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySQL Connector",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            
        }
            System.exit(0);
        
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_backButtonMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
       
        

            
        
       // PreparedStatement ps = conn.preparedStatement("insert into trainer(first_name, last_name, age,date_of_birth,address, gender,phone_number,email,duration, trainer_id, gym_time,category) values(?,?,?,?,?,?,?,?,?,?,?,? )");
//        String first_name  = FirstNameField.getText();
//         last_name = LastNameField.getText();
//        String age  = AgeField.getText();
//        Date date_of_birth = JCalender.getDate();
//        String address = AddressField.getText();
//        if(GenderTextField.isSelected()){
//            
//        }
//        
        
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "This is an information message box", "Information", JOptionPane.INFORMATION_MESSAGE);
            String regex = "\\d{10}";
        if(FirstNameField.getText().equals("")
            || LastNameField.getText().equals("") 
            || AgeField.getText().equals("")
            || JCalender.getDate()==null
            ||  AddressField.getText().equals("")
            || PhoneField.getText().equals("")
            || EmailField.getText().equals("")
            
            || DurationComboBox.getSelectedItem()==null
            || GymTimeComboBox.getSelectedItem() == null
            || jComboBox1.getSelectedItem() == null   ){
                JOptionPane.showMessageDialog(null, "Unfilled Credentials");

        }else if(!(PhoneField.getText().matches(regex))){
            JOptionPane.showMessageDialog(rootPane, "Invalid Contact. Enter contact number with 10 digits and no characters ");
        }else if(!(EmailField.getText().endsWith(".com")) || !(EmailField.getText().contains("@"))) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Email Format");
        }else{
        String first_name = FirstNameField.getText();
        String last_name = LastNameField.getText();
        int age =  Integer.parseInt(AgeField.getText());
        Date date_of_birth  = JCalender.getDate();
        String address = AddressField.getText();
        String gender ;
        if(MaleRadioButton.isSelected()){
            gender = "Male";
        }else if(FemaleRadioButton.isSelected()){
            gender = "Female";
        }else{
            gender = "None";
        }
        String phone_number = PhoneField.getText();
        String email = EmailField.getText();
        String duration = (String) DurationComboBox.getSelectedItem();
        //int trainer_id =  Integer.parseInt(TrainerIDField.getText());
        String gym_time = (String) GymTimeComboBox.getSelectedItem();
        String category = (String)jComboBox1.getSelectedItem();
        Trainer  trainerInput= new Trainer(first_name, last_name,age,date_of_birth,address ,gender , phone_number,  email,duration , gym_time, category);
        
        try {
            trainerDao.addTrainers(trainerInput);
            JOptionPane.showMessageDialog(rootPane, "New Trainer is added successfully. ");
            
        } catch (SQLException ex) {
            Logger.getLogger(TrainerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
         FirstNameField.setText("");
        LastNameField.setText("");
        AgeField.setText("");
        JCalender.setDate(null);
        AddressField.setText("");
        GenderTextField.setText("");
        PhoneField.setText("");
        EmailField.setText("");
        DurationComboBox.setSelectedItem(null);
       // TrainerIDField.setText("");
        GymTimeComboBox.setSelectedItem(null);
        jComboBox1.setSelectedItem(null);
        
        
        }
        
        
     
    }//GEN-LAST:event_RegisterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressText;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeText;
    private javax.swing.JLabel CardioText;
    private javax.swing.JLabel CategoryText;
    private javax.swing.JLabel DOBText;
    private javax.swing.JComboBox<String> DurationComboBox;
    private javax.swing.JLabel DurationText;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel GenderTextField;
    private javax.swing.JComboBox<String> GymTimeComboBox;
    private javax.swing.JLabel GymTimeText;
    private javax.swing.JLabel HomeofFintessText;
    private com.toedter.calendar.JDateChooser JCalender;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneNoText;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RegisterButton1;
    private javax.swing.JLabel TrainerRegText;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
